### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by hacksysteam** [pyoor/distiller#1]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/distiller/seed_inserter.py", line 29, in go
    if not self.seed_exists(seed_name):
  File "/root/distiller/seed_inserter.py", line 16, in seed_exists
    result = self.c.execute("SELECT * FROM key_lookup WHERE seed_name = ?", [seed_name])

OperationalError: database is locked
```

This crash occurred when i started `python server.py -trace -minimize -s ./seed/ -d seed.db -o seed.csv --append &`

**Comment by hacksysteam** [comment]
However, this was caused because I was saving the seed.db on SAMBA share. As soon as I changed the path of seed.db to local, issue seems to be fixed.

Ref [http://stackoverflow.com/questions/2740806/python-sqlite-database-is-locked/30284290#30284290](http://stackoverflow.com/questions/2740806/python-sqlite-database-is-locked/30284290#30284290)

**Comment by hacksysteam** [comment]
Closing this ticket as the crash occurred due to the lock applied by SAMBA.
